# Change these first
owner: wabarc # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Wayback Archiver
    url: https://wabarc.eu.org
  - name: Wayback Archiver Documentation
    url: https://initium.eu.org
  - name: Wayback Archiver Status
    url: https://wabarcstatus.eu.org
  - name: Packages Repository
    url: https://repo.wabarc.eu.org/

status-website:
  name: Wayback Archiver Status
  theme: light
  cname: wabarcstatus.eu.org
  logoUrl: https://avatars.githubusercontent.com/u/66000339
  favicon: 'https://github.com/wabarc/status/raw/main/assets/favicon-32.png'
  faviconSvg: 'https://raw.githubusercontent.com/wabarc/status/main/assets/favicon.svg'
  introTitle: 'Wayback Archiver makes it easy and fast to wayback webpage.'
  introMessage: This is a real-time status page.
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://initium.eu.org
    - title: GitHub
      href: https://github.com/$OWNER
